version: '3.9'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    hostname: db
  pytest:
    image: python:3.10.7
    command: bash -c 'cd /app && python3 -m pip install poetry && poetry install && poetry run python -m pytest'
    depends_on:
      - db
    volumes:
      - .:/app:ro
